# -*- coding: utf-8 -*-
"""ANT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LS9GcDp6RcN6917T5p4t-ss6YY5l8Y_s
"""

from google.colab import drive
drive.mount('/content/drive')

pip install --upgrade tensorflow

"""# CNN with Ant"""

!pip install deap

!pip install keras-tuner

"""# CNN WITH ANT COLONY"""

import os
import numpy as np
import cv2
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from deap import base, creator, tools, algorithms
import random
from sklearn.model_selection import train_test_split

"""


*   **Function to load dataset from directory**
*   **Load datasets**"""

def load_dataset(directory):
    images = []
    labels = []
    for class_name in os.listdir(directory):
        class_dir = os.path.join(directory, class_name)
        for img_name in os.listdir(class_dir):
            img_path = os.path.join(class_dir, img_name)
            img = cv2.imread(img_path)
            img = cv2.resize(img, (32, 32))
            images.append(img)
            labels.append(class_name)
    return np.array(images), np.array(labels)
train_dir = '/content/drive/MyDrive/DATASETS/Facial images dataset for Autism Detection/train'
test_dir = '/content/drive/MyDrive/DATASETS/Facial images dataset for Autism Detection/test'
valid_dir = '/content/drive/MyDrive/DATASETS/Facial images dataset for Autism Detection/valid'
train_imgs, train_labels = load_dataset(train_dir)
test_imgs, test_labels = load_dataset(test_dir)
valid_imgs, valid_labels = load_dataset(valid_dir)

import matplotlib.pyplot as plt

# Function to load and resize images with higher clarity
def load_dataset(directory):
    images = []
    labels = []
    for class_name in os.listdir(directory):
        class_dir = os.path.join(directory, class_name)
        for img_name in os.listdir(class_dir):
            img_path = os.path.join(class_dir, img_name)
            img = cv2.imread(img_path)
            img = cv2.resize(img, (128, 128), interpolation=cv2.INTER_CUBIC)  # Resize with cubic interpolation for better clarity
            images.append(img)
            labels.append(class_name)
    return np.array(images), np.array(labels)

# Function to display 4 images excluding the "Autistic" class
def display_non_autistic_images(images, labels):
    plt.figure(figsize=(8, 8))
    count = 0
    for i in range(len(images)):
        if labels[i] != 'Autistic':  # Exclude "Autistic" class
            plt.subplot(2, 2, count + 1)
            plt.imshow(cv2.cvtColor(images[i], cv2.COLOR_BGR2RGB))  # Convert BGR to RGB for correct color display
            plt.title(labels[i])
            plt.axis('off')
            count += 1
            if count == 4:  # Stop after displaying 4 images
                break
    plt.show()

# Load training and test datasets with higher quality
train_imgs, train_labels = load_dataset(train_dir)
test_imgs, test_labels = load_dataset(test_dir)

# Display 4 images from the training dataset
print("Displaying 4 images from the training dataset:")
display_non_autistic_images(train_imgs, train_labels)

# Display 4 images from the test dataset excluding the "Autistic" class
print("Displaying 4 images from the test dataset (excluding 'Autistic' class):")
display_non_autistic_images(test_imgs, test_labels)

# Function to load and resize images with higher clarity
def load_dataset(directory):
    images = []
    labels = []
    for class_name in os.listdir(directory):
        class_dir = os.path.join(directory, class_name)
        for img_name in os.listdir(class_dir):
            img_path = os.path.join(class_dir, img_name)
            img = cv2.imread(img_path)
            img = cv2.resize(img, (128, 128), interpolation=cv2.INTER_CUBIC)  # Resize with cubic interpolation for better clarity
            images.append(img)
            labels.append(class_name)
    return np.array(images), np.array(labels)

# Function to display 4 images excluding the "Autistic" class
def display_non_autistic_images(images, labels):
    plt.figure(figsize=(8, 8))
    count = 0
    for i in range(len(images)):
        if labels[i] != 'Autistic':  # Exclude "Autistic" class
            plt.subplot(2, 2, count + 1)
            plt.imshow(cv2.cvtColor(images[i], cv2.COLOR_BGR2RGB))  # Convert BGR to RGB
            plt.title(labels[i])
            plt.axis('off')
            count += 1
            if count == 4:  # Stop after displaying 4 images
                break
    plt.show()

# Display 4 images from test data excluding "Autistic" class
test_imgs, test_labels = load_dataset(test_dir)  # Reload test dataset with higher quality
display_non_autistic_images(test_imgs, test_labels)

"""

*   **Normalize the images**
*   **Encode labels**



"""

train_imgs = train_imgs.astype('float32') / 255.0
valid_imgs = valid_imgs.astype('float32') / 255.0
test_imgs = test_imgs.astype('float32') / 255.0
label_encoder = LabelEncoder()
train_labels = label_encoder.fit_transform(train_labels)
valid_labels = label_encoder.transform(valid_labels)
test_labels = label_encoder.transform(test_labels)

"""* **Convert labels to one-hot encoding**"""

num_classes = len(np.unique(train_labels))
train_labels = to_categorical(train_labels, num_classes)
valid_labels = to_categorical(valid_labels, num_classes)
test_labels = to_categorical(test_labels, num_classes)

"""* **Define the CNN model**"""

def create_cnn_model(input_shape, num_classes, optimizer='adam', dropout_rate=0.5):
    model = Sequential()
    model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=input_shape))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(num_classes, activation='softmax'))
    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

"""* **Implement the ACO for feature selection**"""

def evaluate(individual, x_train, y_train, x_val, y_val):
    selected_features = [i for i in range(len(individual)) if individual[i] == 1]
    if len(selected_features) == 0:
        return 0,
    x_train_sel = x_train[..., selected_features]
    x_val_sel = x_val[..., selected_features]
    model = create_cnn_model((32, 32, len(selected_features)), num_classes)
    model.fit(x_train_sel, y_train, epochs=3, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x_val_sel, y_val, verbose=0)
    return accuracy,

"""* **Setup ACO**"""

creator.create("FitnessMax", base.Fitness, weights=(1.0,))
creator.create("Individual", list, fitness=creator.FitnessMax)

toolbox = base.Toolbox()
toolbox.register("attr_bool", random.randint, 0, 1)
toolbox.register("individual", tools.initRepeat, creator.Individual, toolbox.attr_bool, n=32*32*3)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

toolbox.register("mate", tools.cxTwoPoint)
toolbox.register("mutate", tools.mutFlipBit, indpb=0.05)
toolbox.register("select", tools.selTournament, tournsize=3)
toolbox.register("evaluate", evaluate, x_train=train_imgs, y_train=train_labels, x_val=valid_imgs, y_val=valid_labels)

"""* **Manual Grid Search for hyperparameter optimization**"""

def manual_grid_search(x_train, y_train, x_val, y_val, param_grid):
    best_score = 0
    best_params = None
    for optimizer in param_grid['optimizer']:
        for dropout_rate in param_grid['dropout_rate']:
            model = create_cnn_model((32, 32, 3), num_classes, optimizer=optimizer, dropout_rate=dropout_rate)
            model.fit(x_train, y_train, epochs=10, batch_size=32, verbose=0)
            _, accuracy = model.evaluate(x_val, y_val, verbose=0)
            print(f"Optimizer: {optimizer}, Dropout Rate: {dropout_rate}, Validation Accuracy: {accuracy}")
            if accuracy > best_score:
                best_score = accuracy
                best_params = {'optimizer': optimizer, 'dropout_rate': dropout_rate}
    return best_score, best_params

"""* **Split training data into train and validation sets for grid search**"""

x_train_split, x_val_split, y_train_split, y_val_split = train_test_split(train_imgs, train_labels, test_size=0.2, random_state=42)

# Print the shapes of the training and validation images and labels
print("Training images shape:", x_train_split.shape)
print("Validation images shape:", x_val_split.shape)
print("Training labels shape:", y_train_split.shape)
print("Validation labels shape:", y_val_split.shape)

param_grid = {
    'optimizer': ['adam', 'sgd'],
    'dropout_rate': [0.3, 0.5, 0.7]
}

x_train_split, x_val_split, y_train_split, y_val_split = train_test_split(train_imgs, train_labels, test_size=0.2, random_state=42)
best_score, best_params = manual_grid_search(x_train_split, y_train_split, x_val_split, y_val_split, param_grid)
print(f"Best Score: {best_score} using {best_params}")



best_score, best_params = manual_grid_search(x_train_split, y_train_split, x_val_split, y_val_split, param_grid)
print(f"Best Score: {best_score} using {best_params}")



"""* **Evaluate the best model**"""

best_model = create_cnn_model((32, 32, 3), num_classes, optimizer=best_params['optimizer'], dropout_rate=best_params['dropout_rate'])
best_model.fit(train_imgs, train_labels, epochs=10, batch_size=32, verbose=0)
loss, accuracy = best_model.evaluate(test_imgs, test_labels, verbose=0)
print(f'Test accuracy: {accuracy}')

"""* **Generate classification report and confusion matrix**"""

test_pred = best_model.predict(test_imgs)
test_pred_classes = np.argmax(test_pred, axis=1)
test_true_classes = np.argmax(test_labels, axis=1)
print(classification_report(test_true_classes, test_pred_classes, target_names=label_encoder.classes_))
conf_matrix = confusion_matrix(test_true_classes, test_pred_classes)

# Plot confusion matrix
plt.figure(figsize=(10, 8))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

# Plotting training & validation accuracy values
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(['Train', 'Validation'], loc='upper left')

# Plotting training & validation loss values
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

best_model.save('CNN_Ant.h5')

"""# VGG"""

import os
import numpy as np
import cv2
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.applications import VGG16
from keras.optimizers import Adam
from deap import base, creator, tools, algorithms
import random
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
import matplotlib.pyplot as plt
import seaborn as sns

def load_dataset(directory):
    images = []
    labels = []
    for class_name in os.listdir(directory):
        class_dir = os.path.join(directory, class_name)
        for img_name in os.listdir(class_dir):
            img_path = os.path.join(class_dir, img_name)
            img = cv2.imread(img_path)
            img = cv2.resize(img, (224, 224))  # Adjust the size to VGG input size
            images.append(img)
            labels.append(class_name)
    return np.array(images), np.array(labels)

train_dir = '/content/drive/MyDrive/DATASETS/Facial images dataset for Autism Detection/train'
test_dir = '/content/drive/MyDrive/DATASETS/Facial images dataset for Autism Detection/test'
valid_dir = '/content/drive/MyDrive/DATASETS/Facial images dataset for Autism Detection/valid'

train_imgs, train_labels = load_dataset(train_dir)
test_imgs, test_labels = load_dataset(test_dir)
valid_imgs, valid_labels = load_dataset(valid_dir)

train_imgs = train_imgs.astype('float32') / 255.0
valid_imgs = valid_imgs.astype('float32') / 255.0
test_imgs = test_imgs.astype('float32') / 255.0

label_encoder = LabelEncoder()
train_labels = label_encoder.fit_transform(train_labels)
valid_labels = label_encoder.transform(valid_labels)
test_labels = label_encoder.transform(test_labels)

num_classes = len(np.unique(train_labels))
train_labels = to_categorical(train_labels, num_classes)
valid_labels = to_categorical(valid_labels, num_classes)
test_labels = to_categorical(test_labels, num_classes)

vgg_base = VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

# Freeze layers in the base model
for layer in vgg_base.layers:
    layer.trainable = False

# Add custom classifier on top of the VGG16 base
model = Sequential()
model.add(vgg_base)
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Training the model and capturing history
history = model.fit(train_imgs, train_labels, epochs=10, batch_size=32, validation_data=(valid_imgs, valid_labels))

# Plotting training & validation accuracy values
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(['Train', 'Validation'], loc='upper left')

# Plotting training & validation loss values
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

loss, accuracy = model.evaluate(test_imgs, test_labels)
print(f'Test accuracy: {accuracy}')

test_pred = model.predict(test_imgs)
test_pred_classes = np.argmax(test_pred, axis=1)
test_true_classes = np.argmax(test_labels, axis=1)

# Calculate additional metrics
accuracy = accuracy_score(test_true_classes, test_pred_classes)
precision = precision_score(test_true_classes, test_pred_classes, average='weighted')
recall = recall_score(test_true_classes, test_pred_classes, average='weighted')
f1 = f1_score(test_true_classes, test_pred_classes, average='weighted')
print(f'Accuracy: {accuracy}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'F1 Score: {f1}')
print(classification_report(test_true_classes, test_pred_classes, target_names=label_encoder.classes_))

conf_matrix = confusion_matrix(test_true_classes, test_pred_classes)

# Plot confusion matrix
plt.figure(figsize=(10, 8))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

# Visualize data distribution and class balance
plt.figure(figsize=(8, 6))
sns.countplot(x=label_encoder.inverse_transform(train_labels.argmax(axis=1)))
plt.title('Class Distribution in Training Data')
plt.xlabel('Class')
plt.ylabel('Count')
plt.show()

import matplotlib.image as mpimg

# Make predictions on the test dataset
predictions = model.predict(test_imgs)

# Convert the predictions from one-hot encoded to class labels
predicted_classes = np.argmax(predictions, axis=1)
true_classes = np.argmax(test_labels, axis=1)

# Get the class names from the label encoder
class_names = label_encoder.inverse_transform(predicted_classes)

# Let's visualize some predictions against the test images
plt.figure(figsize=(12, 12))
for val, i in enumerate(test_imgs[:10]):
    plt.subplot(5, 2, val + 1)
    plt.imshow(cv2.cvtColor(i, cv2.COLOR_BGR2RGB))  # Convert BGR (OpenCV) to RGB for displaying
    plt.title(f"Prediction: {class_names[val]}")  # Display predicted class name
    plt.axis('off')
plt.tight_layout()
plt.show()





