# -*- coding: utf-8 -*-
"""Artificial Bee Colony

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wKIoTQdI2ZfiJ8rFo4_XR6ybwjzqMUlF

# Artificial Bee Colony with CNN
"""

from google.colab import drive
drive.mount('/content/drive')

"""* **Importing Libraries**"""

import os
import numpy as np
import cv2
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from abc import ABC, abstractmethod
import random

"""


*   **Function to load dataset from directory**
*   **Load datasets**"""

def load_dataset(directory):
    images = []
    labels = []
    for class_name in os.listdir(directory):
        class_dir = os.path.join(directory, class_name)
        for img_name in os.listdir(class_dir):
            img_path = os.path.join(class_dir, img_name)
            img = cv2.imread(img_path)
            img = cv2.resize(img, (32, 32))
            images.append(img)
            labels.append(class_name)
    return np.array(images), np.array(labels)
train_dir = '/content/drive/MyDrive/autistic_train'
test_dir = '/content/drive/MyDrive/autistic_test'
valid_dir = '/content/drive/MyDrive/autistic_valid'
train_imgs, train_labels = load_dataset(train_dir)
test_imgs, test_labels = load_dataset(test_dir)
valid_imgs, valid_labels = load_dataset(valid_dir)

"""

*   **Normalize the images**
*   **Encode labels**



"""

train_imgs = train_imgs.astype('float32') / 255.0
valid_imgs = valid_imgs.astype('float32') / 255.0
test_imgs = test_imgs.astype('float32') / 255.0
label_encoder = LabelEncoder()
train_labels = label_encoder.fit_transform(train_labels)
valid_labels = label_encoder.transform(valid_labels)
test_labels = label_encoder.transform(test_labels)

"""* **Convert labels to one-hot encoding**"""

num_classes = len(np.unique(train_labels))
train_labels = to_categorical(train_labels, num_classes)
valid_labels = to_categorical(valid_labels, num_classes)
test_labels = to_categorical(test_labels, num_classes)

"""* **Define the CNN model**"""

def create_cnn_model(input_shape, num_classes, optimizer='adam', dropout_rate=0.5):
    model = Sequential()
    model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=input_shape))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(num_classes, activation='softmax'))
    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

"""* **Implement the ABC for feature selection**"""

# Implement the ABC for feature selection
class Bee(ABC):
    @abstractmethod
    def search(self): pass

class EmployedBee(Bee):
    def __init__(self, food_source, fitness):
        self.food_source = food_source
        self.fitness = fitness

    def search(self):
        new_food_source = self.food_source[:]
        index_to_change = random.randint(0, len(new_food_source) - 1)
        new_food_source[index_to_change] = 1 - new_food_source[index_to_change]
        return new_food_source

class OnlookerBee(Bee):
    def __init__(self, employed_bees):
        self.employed_bees = employed_bees

    def search(self):
        selected_bee = random.choices(self.employed_bees, weights=[bee.fitness for bee in self.employed_bees])[0]
        return selected_bee.search()

class ScoutBee(Bee):
    def __init__(self, feature_size):
        self.feature_size = feature_size

    def search(self):
        return [random.randint(0, 1) for _ in range(self.feature_size)]

def evaluate(individual, x_train, y_train, x_val, y_val):
    selected_features = [i for i in range(len(individual)) if individual[i] == 1]
    if len(selected_features) == 0:
        return 0,

    x_train_sel = x_train[..., selected_features]
    x_val_sel = x_val[..., selected_features]

    model = create_cnn_model((32, 32, len(selected_features)), num_classes)
    model.fit(x_train_sel, y_train, epochs=3, batch_size=32, verbose=0)

    _, accuracy = model.evaluate(x_val_sel, y_val, verbose=0)
    return accuracy,

"""* **Setup ABC**"""

class ArtificialBeeColony:
    def __init__(self, population_size, feature_size, x_train, y_train, x_val, y_val, max_iterations=20):
        self.population_size = population_size
        self.feature_size = feature_size
        self.max_iterations = max_iterations
        self.x_train = x_train
        self.y_train = y_train
        self.x_val = x_val
        self.y_val = y_val

        self.employed_bees = []
        for _ in range(population_size // 2):
            scout = ScoutBee(feature_size)
            food_source = scout.search()
            fitness = evaluate(food_source, x_train, y_train, x_val, y_val)[0]
            self.employed_bees.append(EmployedBee(food_source, fitness))

        self.onlooker_bees = [OnlookerBee(self.employed_bees) for _ in range(population_size // 2)]

    def optimize(self):
        best_solution = None
        best_fitness = 0

        for _ in range(self.max_iterations):
            for bee in self.employed_bees:
                new_food_source = bee.search()
                new_fitness = evaluate(new_food_source, self.x_train, self.y_train, self.x_val, self.y_val)[0]
                if new_fitness > bee.fitness:
                    bee.food_source = new_food_source
                    bee.fitness = new_fitness

            for bee in self.onlooker_bees:
                new_food_source = bee.search()
                new_fitness = evaluate(new_food_source, self.x_train, self.y_train, self.x_val, self.y_val)[0]
                if new_fitness > bee.employed_bees[0].fitness:
                    bee.employed_bees[0].food_source = new_food_source
                    bee.employed_bees[0].fitness = new_fitness

            self.employed_bees.sort(key=lambda b: b.fitness, reverse=True)
            if self.employed_bees[0].fitness > best_fitness:
                best_solution = self.employed_bees[0].food_source
                best_fitness = self.employed_bees[0].fitness

        return best_solution, best_fitness

"""* **Manual Grid Search for hyperparameter optimization**"""

def manual_grid_search(x_train, y_train, x_val, y_val, param_grid):
    best_score = 0
    best_params = None
    for optimizer in param_grid['optimizer']:
        for dropout_rate in param_grid['dropout_rate']:
            model = create_cnn_model((32, 32, 3), num_classes, optimizer=optimizer, dropout_rate=dropout_rate)
            model.fit(x_train, y_train, epochs=10, batch_size=32, verbose=0)
            _, accuracy = model.evaluate(x_val, y_val, verbose=0)
            print(f"Optimizer: {optimizer}, Dropout Rate: {dropout_rate}, Validation Accuracy: {accuracy}")
            if accuracy > best_score:
                best_score = accuracy
                best_params = {'optimizer': optimizer, 'dropout_rate': dropout_rate}
    return best_score, best_params

"""* **Split training data into train and validation sets for grid search**"""

x_train_split, x_val_split, y_train_split, y_val_split = train_test_split(train_imgs, train_labels, test_size=0.2, random_state=42)

param_grid = {
    'optimizer': ['adam', 'sgd'],
    'dropout_rate': [0.3, 0.5, 0.7]
}

best_score, best_params = manual_grid_search(x_train_split, y_train_split, x_val_split, y_val_split, param_grid)
print(f"Best Score: {best_score} using {best_params}")

"""* **Evaluate the best model**"""

best_model = create_cnn_model((32, 32, 3), num_classes, optimizer=best_params['optimizer'], dropout_rate=best_params['dropout_rate'])
best_model.fit(train_imgs, train_labels, epochs=10, batch_size=32, verbose=0)
loss, accuracy = best_model.evaluate(test_imgs, test_labels, verbose=0)
print(f'Test accuracy: {accuracy}')

best_model.save('CNN_Artificial.h5')

"""* **Generate classification report and confusion matrix**"""

test_pred = best_model.predict(test_imgs)
test_pred_classes = np.argmax(test_pred, axis=1)
test_true_classes = np.argmax(test_labels, axis=1)
print(classification_report(test_true_classes, test_pred_classes, target_names=label_encoder.classes_))
conf_matrix = confusion_matrix(test_true_classes, test_pred_classes)

# Plot confusion matrix
plt.figure(figsize=(10, 8))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

"""# Artificial Bee Colony with VGG"""

import os
import numpy as np
import cv2
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from abc import ABC, abstractmethod
import random

"""* **Function to load dataset from directory**"""

def load_dataset(directory):
    images = []
    labels = []
    for class_name in os.listdir(directory):
        class_dir = os.path.join(directory, class_name)
        for img_name in os.listdir(class_dir):
            img_path = os.path.join(class_dir, img_name)
            img = cv2.imread(img_path)
            img = cv2.resize(img, (32, 32))
            images.append(img)
            labels.append(class_name)
    return np.array(images), np.array(labels)
train_dir = '/content/drive/MyDrive/autistic_train'
test_dir = '/content/drive/MyDrive/autistic_test'
valid_dir = '/content/drive/MyDrive/autistic_valid'
train_imgs, train_labels = load_dataset(train_dir)
test_imgs, test_labels = load_dataset(test_dir)
valid_imgs, valid_labels = load_dataset(valid_dir)
print(train_imgs.shape, train_labels.shape)
print(test_imgs.shape, test_labels.shape)
print(valid_imgs.shape, valid_labels.shape)

"""* **Normalize the images**
* **Encode labels**
"""

train_imgs = train_imgs.astype('float32') / 255.0
valid_imgs = valid_imgs.astype('float32') / 255.0
test_imgs = test_imgs.astype('float32') / 255.0
label_encoder = LabelEncoder()
train_labels = label_encoder.fit_transform(train_labels)
valid_labels = label_encoder.transform(valid_labels)
test_labels = label_encoder.transform(test_labels)
num_classes = len(np.unique(train_labels))
train_labels = to_categorical(train_labels, num_classes)
valid_labels = to_categorical(valid_labels, num_classes)
test_labels = to_categorical(test_labels, num_classes)

"""* **Load pre-trained VGG16 model**"""

def create_vgg_model(input_shape, num_classes, optimizer='adam', dropout_rate=0.5):
    model = Sequential()
    model.add(Conv2D(64, kernel_size=(3, 3), activation='relu', padding='same', input_shape=input_shape))
    model.add(Conv2D(64, kernel_size=(3, 3), activation='relu', padding='same'))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    model.add(Conv2D(128, kernel_size=(3, 3), activation='relu', padding='same'))
    model.add(Conv2D(128, kernel_size=(3, 3), activation='relu', padding='same'))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    model.add(Conv2D(256, kernel_size=(3, 3), activation='relu', padding='same'))
    model.add(Conv2D(256, kernel_size=(3, 3), activation='relu', padding='same'))
    model.add(Conv2D(256, kernel_size=(3, 3), activation='relu', padding='same'))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    model.add(Flatten())
    model.add(Dense(512, activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(512, activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(num_classes, activation='softmax'))

    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

"""* **Implement the ABC for feature selection**"""

class Bee(ABC):
    @abstractmethod
    def search(self): pass

class EmployedBee(Bee):
    def __init__(self, food_source, fitness):
        self.food_source = food_source
        self.fitness = fitness

    def search(self):
        new_food_source = self.food_source[:]
        index_to_change = random.randint(0, len(new_food_source) - 1)
        new_food_source[index_to_change] = 1 - new_food_source[index_to_change]
        return new_food_source

class OnlookerBee(Bee):
    def __init__(self, employed_bees):
        self.employed_bees = employed_bees

    def search(self):
        selected_bee = random.choices(self.employed_bees, weights=[bee.fitness for bee in self.employed_bees])[0]
        return selected_bee.search()

class ScoutBee(Bee):
    def __init__(self, feature_size):
        self.feature_size = feature_size

    def search(self):
        return [random.randint(0, 1) for _ in range(self.feature_size)]

def evaluate(individual, x_train, y_train, x_val, y_val):
    selected_features = [i for i in range(len(individual)) if individual[i] == 1]
    if len(selected_features) == 0:
        return 0,

    x_train_sel = x_train[..., selected_features]
    x_val_sel = x_val[..., selected_features]

    model = create_vgg_model((32, 32, len(selected_features)), num_classes)
    model.fit(x_train_sel, y_train, epochs=3, batch_size=32, verbose=0)

    _, accuracy = model.evaluate(x_val_sel, y_val, verbose=0)
    return accuracy,

# Setup ABC
class ArtificialBeeColony:
    def __init__(self, population_size, feature_size, x_train, y_train, x_val, y_val, max_iterations=20):
        self.population_size = population_size
        self.feature_size = feature_size
        self.max_iterations = max_iterations
        self.x_train = x_train
        self.y_train = y_train
        self.x_val = x_val
        self.y_val = y_val

        self.employed_bees = []
        for _ in range(population_size // 2):
            scout = ScoutBee(feature_size)
            food_source = scout.search()
            fitness = evaluate(food_source, x_train, y_train, x_val, y_val)[0]
            self.employed_bees.append(EmployedBee(food_source, fitness))

        self.onlooker_bees = [OnlookerBee(self.employed_bees) for _ in range(population_size // 2)]

    def optimize(self):
        best_solution = None
        best_fitness = 0

        for _ in range(self.max_iterations):
            for bee in self.employed_bees:
                new_food_source = bee.search()
                new_fitness = evaluate(new_food_source, self.x_train, self.y_train, self.x_val, self.y_val)[0]
                if new_fitness > bee.fitness:
                    bee.food_source = new_food_source
                    bee.fitness = new_fitness

            for bee in self.onlooker_bees:
                new_food_source = bee.search()
                new_fitness = evaluate(new_food_source, self.x_train, self.y_train, self.x_val, self.y_val)[0]
                if new_fitness > bee.employed_bees[0].fitness:
                    bee.employed_bees[0].food_source = new_food_source
                    bee.employed_bees[0].fitness = new_fitness

            self.employed_bees.sort(key=lambda b: b.fitness, reverse=True)
            if self.employed_bees[0].fitness > best_fitness:
                best_solution = self.employed_bees[0].food_source
                best_fitness = self.employed_bees[0].fitness

        return best_solution, best_fitness

"""* **Manual Grid Search for hyperparameter optimization**"""

def manual_grid_search(x_train, y_train, x_val, y_val, param_grid):
    best_score = 0
    best_params = None
    for optimizer in param_grid['optimizer']:
        for dropout_rate in param_grid['dropout_rate']:
            model = create_vgg_model((32, 32, 3), num_classes, optimizer=optimizer, dropout_rate=dropout_rate)
            model.fit(x_train, y_train, epochs=10, batch_size=32, verbose=0)
            _, accuracy = model.evaluate(x_val, y_val, verbose=0)
            print(f"Optimizer: {optimizer}, Dropout Rate: {dropout_rate}, Validation Accuracy: {accuracy}")
            if accuracy > best_score:
                best_score = accuracy
                best_params = {'optimizer': optimizer, 'dropout_rate': dropout_rate}
    return best_score, best_params

x_train_split, x_val_split, y_train_split, y_val_split = train_test_split(train_imgs, train_labels, test_size=0.2, random_state=42)

param_grid = {
    'optimizer': ['adam', 'sgd'],
    'dropout_rate': [0.3, 0.5, 0.7]
}

best_score, best_params = manual_grid_search(x_train_split, y_train_split, x_val_split, y_val_split, param_grid)
print(f"Best Score: {best_score} using {best_params}")

"""* **Generate classification report and confusion matrix**"""

# Evaluate the best model
best_model = create_vgg_model((32, 32, 3), num_classes, optimizer=best_params['optimizer'], dropout_rate=best_params['dropout_rate'])
best_model.fit(train_imgs, train_labels, epochs=10, batch_size=32, verbose=0)
loss, accuracy = best_model.evaluate(test_imgs, test_labels, verbose=0)
print(f'Test accuracy: {accuracy}')

# Generate classification report and confusion matrix
test_pred = best_model.predict(test_imgs)
test_pred_classes = np.argmax(test_pred, axis=1)
test_true_classes = np.argmax(test_labels, axis=1)
print(classification_report(test_true_classes, test_pred_classes, target_names=label_encoder.classes_))
conf_matrix = confusion_matrix(test_true_classes, test_pred_classes)

# Plot confusion matrix
plt.figure(figsize=(10, 8))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

best_model.save("VGG_Artificial.h5")

!pip install deap

"""# Artificial Bee Colony With Resnet"""

import os
import numpy as np
import cv2
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.applications import ResNet50
from keras.layers import Dense, GlobalAveragePooling2D, Dropout
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from deap import base, creator, tools, algorithms
import random

# Function to load dataset from directory
def load_dataset(directory):
    images = []
    labels = []
    for class_name in os.listdir(directory):
        class_dir = os.path.join(directory, class_name)
        for img_name in os.listdir(class_dir):
            img_path = os.path.join(class_dir, img_name)
            img = cv2.imread(img_path)
            img = cv2.resize(img, (224, 224))  # ResNet expects 224x224 images
            images.append(img)
            labels.append(class_name)
    return np.array(images), np.array(labels)

# Define ResNet model creation function
def create_resnet_model(input_shape, num_classes, optimizer='adam', dropout_rate=0.5):
    base_model = ResNet50(include_top=False, weights='imagenet', input_shape=input_shape)
    model = Sequential()
    model.add(base_model)
    model.add(GlobalAveragePooling2D())
    model.add(Dense(512, activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(num_classes, activation='softmax'))

    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
    return model
# Load and preprocess datasets
train_dir = '/content/drive/MyDrive/autistic_train'
test_dir = '/content/drive/MyDrive/autistic_test'
valid_dir = '/content/drive/MyDrive/autistic_valid'
train_imgs, train_labels = load_dataset(train_dir)
test_imgs, test_labels = load_dataset(test_dir)
valid_imgs, valid_labels = load_dataset(valid_dir)

train_imgs = train_imgs.astype('float32') / 255.0
valid_imgs = valid_imgs.astype('float32') / 255.0
test_imgs = test_imgs.astype('float32') / 255.0

label_encoder = LabelEncoder()
train_labels = label_encoder.fit_transform(train_labels)
valid_labels = label_encoder.transform(valid_labels)
test_labels = label_encoder.transform(test_labels)

num_classes = len(np.unique(train_labels))
train_labels = to_categorical(train_labels, num_classes)
valid_labels = to_categorical(valid_labels, num_classes)
test_labels = to_categorical(test_labels, num_classes)

# Split training data into train and validation sets for grid search
x_train_split, x_val_split, y_train_split, y_val_split = train_test_split(train_imgs, train_labels, test_size=0.2, random_state=42)

# Define DEAP setup for ABC algorithm
creator.create("FitnessMax", base.Fitness, weights=(1.0,))
creator.create("Individual", list, fitness=creator.FitnessMax)

toolbox = base.Toolbox()
toolbox.register("attr_bool", random.randint, 0, 1)
toolbox.register("individual", tools.initRepeat, creator.Individual, toolbox.attr_bool, n=2)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)
toolbox.register("mate", tools.cxTwoPoint)
toolbox.register("mutate", tools.mutFlipBit, indpb=0.05)
toolbox.register("evaluate", lambda ind: evaluate(ind, x_train_split, y_train_split, x_val_split, y_val_split))
toolbox.register("select", tools.selBest)

# Function to evaluate the fitness of an individual
def evaluate(individual, x_train, y_train, x_val, y_val):
    optimizers = ['adam', 'sgd']
    dropout_rates = [0.3, 0.5]

    optimizer = optimizers[individual[0]]
    dropout_rate = dropout_rates[individual[1]]

    model = create_resnet_model((224, 224, 3), num_classes, optimizer=optimizer, dropout_rate=dropout_rate)
    model.fit(x_train, y_train, epochs=3, batch_size=32, verbose=0)

    _, accuracy = model.evaluate(x_val, y_val, verbose=0)
    return accuracy,

# Set parameters for ABC
ngen = 10  # Number of generations
npop = 10  # Population size

# Run ABC algorithm
def abc_algorithm(toolbox, ngen, npop):
    population = toolbox.population(n=npop)
    for gen in range(ngen):
        fits = toolbox.map(toolbox.evaluate, population)
        for fit, ind in zip(fits, population):
            ind.fitness.values = fit
        offspring = algorithms.varAnd(population, toolbox, cxpb=0.5, mutpb=0.2)
        fits = toolbox.map(toolbox.evaluate, offspring)
        for fit, ind in zip(fits, offspring):
            ind.fitness.values = fit
        population = toolbox.select(offspring + population, k=npop)
    return population

# Run ABC algorithm
final_population = abc_algorithm(toolbox, ngen, npop)

# Select the best individual from the final population
best_individual = tools.selBest(final_population, k=1)[0]

# Extract best parameters
best_optimizer = ['adam', 'sgd'][best_individual[0]]
best_dropout_rate = [0.3, 0.5][best_individual[1]]
print(f"Best parameters - Optimizer: {best_optimizer}, Dropout Rate: {best_dropout_rate}")

# Final model evaluation with best parameters
best_model = create_resnet_model((224, 224, 3), num_classes, optimizer=best_optimizer, dropout_rate=best_dropout_rate)
best_model.fit(train_imgs, train_labels, epochs=10, batch_size=32, verbose=0)
loss, accuracy = best_model.evaluate(test_imgs, test_labels, verbose=0)
print(f'Test accuracy: {accuracy}')

# Generate classification report and confusion matrix
test_pred = best_model.predict(test_imgs)
test_pred_classes = np.argmax(test_pred, axis=1)
test_true_classes = np.argmax(test_labels, axis=1)
print(classification_report(test_true_classes, test_pred_classes, target_names=label_encoder.classes_))
conf_matrix = confusion_matrix(test_true_classes, test_pred_classes)

# Plot confusion matrix
plt.figure(figsize=(10, 8))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

