# -*- coding: utf-8 -*-
"""Fire Fly

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mo33DFaeAokcTLBTR6hUVIL5xeMeK_hI
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Data"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
#from pyswarm import pso
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('/content/Toddler Autism dataset July 2018.csv')
data

data.columns

data.isnull().sum()

data.duplicated().sum()

data.info()

data.describe()

data.head()

"""**Encode categorical variables**"""

label_encoders = {}
categorical_columns = ['Sex', 'Ethnicity', 'Jaundice', 'Family_mem_with_ASD', 'Who completed the test','Class/ASD Traits ']
for column in categorical_columns:
    label_encoders[column] = LabelEncoder()
    data[column] = label_encoders[column].fit_transform(data[column])

X = data.drop(['Case_No', 'Class/ASD Traits '], axis=1)
y = data['Class/ASD Traits ']

"""**Feature scaling using StandardScaler**"""

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=15)  # Adjust n_components based on the dataset
X_reduced = pca.fit_transform(X_scaled)

pca



"""# 1) MLP Classifier

**Define Fire Fly Optimization objective function for feature selection**
"""

def objective_function(features, X, y):
    features = np.array(features).astype(bool)
    if not np.any(features):  # Ensure at least one feature is selected
        return float('inf')  # Return a high value for invalid solutions
    X_selected = X[:, features]

    X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)

    clf = MLPClassifier(max_iter=1000, random_state=52)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    return -accuracy_score(y_test, y_pred)

# Firefly Algorithm
class FireflyAlgorithm:
    def __init__(self, objective_function, lb, ub, args=(), pop_size=20, max_iter=50, alpha=0.5, beta_min=0.2, gamma=1.0):
        self.objective_function = objective_function
        self.lb = np.array(lb)
        self.ub = np.array(ub)
        self.args = args
        self.pop_size = pop_size
        self.max_iter = max_iter
        self.alpha = alpha
        self.beta_min = beta_min
        self.gamma = gamma

    def run(self):
        dim = len(self.lb)
        population = np.random.randint(2, size=(self.pop_size, dim))
        fitness = np.apply_along_axis(self.objective_function, 1, population, *self.args)

        best_firefly = population[np.argmin(fitness)]
        best_fitness = np.min(fitness)

        for t in range(self.max_iter):
            for i in range(self.pop_size):
                for j in range(self.pop_size):
                    if fitness[i] > fitness[j]:
                        r = np.linalg.norm(population[i] - population[j])
                        beta = self.beta_min + (1 - self.beta_min) * np.exp(-self.gamma * r ** 2)
                        population[i] = population[i] + beta * (population[j] - population[i]) + \
                                        self.alpha * (np.random.rand(dim) - 0.5)
                        population[i] = np.clip(population[i], self.lb, self.ub)
                        population[i] = np.round(population[i])
                        if not np.any(population[i]):  # Ensure at least one feature is selected
                            population[i][np.random.randint(dim)] = 1
                        fitness[i] = self.objective_function(population[i], *self.args)

            best_firefly = population[np.argmin(fitness)]
            best_fitness = np.min(fitness)

        return best_firefly, best_fitness

num_features = X_reduced.shape[1]
lb = [0] * num_features
ub = [1] * num_features

fa = FireflyAlgorithm(objective_function, lb, ub, args=(X_reduced, y), pop_size=10, max_iter=25)
best_features, _ = fa.run()

# Select best features
X_selected = X_reduced[:, best_features.astype(bool)]

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=52)

"""**Define parameter grid for ANN**"""

# Define parameter grid for ANN
param_grid = {
    'hidden_layer_sizes': [(50,), (30, 30)],
    'activation': ['relu', 'tanh'],
    'solver': ['adam', 'sgd'],
    'alpha': [0.01, 0.1],  # Increase alpha for stronger regularization
    'learning_rate': ['constant', 'adaptive']
}

"""**Grid search based optimization**"""

grid_search = GridSearchCV(MLPClassifier(max_iter=1000, random_state=52), param_grid, cv=5, n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)

# Best parameters
best_params = grid_search.best_params_

# Train the model with best parameters
best_clf = MLPClassifier(max_iter=1000, random_state=52, **best_params)
best_clf.fit(X_train, y_train)

# Predictions
y_pred_train = best_clf.predict(X_train)
y_pred_test = best_clf.predict(X_test)

# Accuracy
train_accuracy = accuracy_score(y_train, y_pred_train)
test_accuracy = accuracy_score(y_test, y_pred_test)

print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)
print("Best Parameters:", best_clf.get_params())
print("Best Parameters:", best_params)

clf = MLPClassifier(max_iter=1000, random_state=42, early_stopping=True)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Final accuracy with selected features:", accuracy)

"""**Classification Report**"""

print("\nClassification Report (Train):")
print(classification_report(y_train, y_pred_train))
print("\nClassification Report (Test):")
print(classification_report(y_test, y_pred_test))

# Confusion Matrix
conf_matrix_train = confusion_matrix(y_train, y_pred_train)
conf_matrix_test = confusion_matrix(y_test, y_pred_test)

plt.figure(figsize=(14, 5))

plt.subplot(1, 2, 1)
sns.heatmap(conf_matrix_train, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix - Train')
plt.xlabel('Predicted')
plt.ylabel('True')

plt.subplot(1, 2, 2)
sns.heatmap(conf_matrix_test, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix - Test')
plt.xlabel('Predicted')
plt.ylabel('True')

plt.tight_layout()
plt.show()

import pickle
with open('ANNmodelFF.pkl', 'wb') as file:
    pickle.dump(clf, file)

"""# DV"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('/content/Toddler Autism dataset July 2018.csv')

# Label encoding for categorical features
label_encoders = {}
categorical_columns = ['Sex', 'Ethnicity', 'Jaundice', 'Family_mem_with_ASD', 'Who completed the test', 'Class/ASD Traits ']
for column in categorical_columns:
    label_encoders[column] = LabelEncoder()
    data[column] = label_encoders[column].fit_transform(data[column])

# Drop the target column and case number
X = data.drop(['Case_No', 'Class/ASD Traits '], axis=1)
y = data['Class/ASD Traits ']

# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Apply PCA
pca = PCA(n_components=15)
X_reduced = pca.fit_transform(X_scaled)

# Define the objective function for Firefly Algorithm
def objective_function(features, X, y):
    features = np.array(features).astype(bool)
    if not np.any(features):  # Ensure at least one feature is selected
        return float('inf')  # Return a high value for invalid solutions
    X_selected = X[:, features]

    X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)

    clf = MLPClassifier(max_iter=1000, random_state=52)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    return -accuracy_score(y_test, y_pred)

# Firefly Algorithm
class FireflyAlgorithm:
    def __init__(self, objective_function, lb, ub, args=(), pop_size=20, max_iter=50, alpha=0.5, beta_min=0.2, gamma=1.0):
        self.objective_function = objective_function
        self.lb = np.array(lb)
        self.ub = np.array(ub)
        self.args = args
        self.pop_size = pop_size
        self.max_iter = max_iter
        self.alpha = alpha
        self.beta_min = beta_min
        self.gamma = gamma

    def run(self):
        dim = len(self.lb)
        population = np.random.randint(2, size=(self.pop_size, dim))
        fitness = np.apply_along_axis(self.objective_function, 1, population, *self.args)

        best_firefly = population[np.argmin(fitness)]
        best_fitness = np.min(fitness)

        for t in range(self.max_iter):
            for i in range(self.pop_size):
                for j in range(self.pop_size):
                    if fitness[i] > fitness[j]:
                        r = np.linalg.norm(population[i] - population[j])
                        beta = self.beta_min + (1 - self.beta_min) * np.exp(-self.gamma * r ** 2)
                        population[i] = population[i] + beta * (population[j] - population[i]) + \
                                        self.alpha * (np.random.rand(dim) - 0.5)
                        population[i] = np.clip(population[i], self.lb, self.ub)
                        population[i] = np.round(population[i])
                        if not np.any(population[i]):  # Ensure at least one feature is selected
                            population[i][np.random.randint(dim)] = 1
                        fitness[i] = self.objective_function(population[i], *self.args)

            best_firefly = population[np.argmin(fitness)]
            best_fitness = np.min(fitness)

        return best_firefly, best_fitness

# Example of how to use the FireflyAlgorithm
dim = X_reduced.shape[1]
firefly = FireflyAlgorithm(objective_function, lb=[0] * dim, ub=[1] * dim, args=(X_reduced, y), pop_size=20, max_iter=50)
best_features, best_fitness = firefly.run()

# Select best features
X_selected = X_reduced[:, best_features.astype(bool)]

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=52)

# Define parameter grid for ANN
param_grid = {
    'hidden_layer_sizes': [(50,), (30, 30)],
    'activation': ['relu', 'tanh'],
    'solver': ['adam', 'sgd'],
    'alpha': [0.01, 0.1],  # Increase alpha for stronger regularization
    'learning_rate': ['constant', 'adaptive']
}

# Train the model using GridSearchCV
grid_search = GridSearchCV(MLPClassifier(max_iter=1000, random_state=52), param_grid, cv=3)
grid_search.fit(X_train, y_train)

# Get the best classifier
best_clf = grid_search.best_estimator_
best_params = grid_search.best_params_

# Predictions
y_pred_train = best_clf.predict(X_train)
y_pred_test = best_clf.predict(X_test)

# Accuracy
train_accuracy = accuracy_score(y_train, y_pred_train)
test_accuracy = accuracy_score(y_test, y_pred_test)

print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)
print("Best Parameters:", best_params)

print("\nClassification Report (Train):")
print(classification_report(y_train, y_pred_train))

print("\nClassification Report (Test):")
print(classification_report(y_test, y_pred_test))

# Confusion Matrix
conf_matrix_train = confusion_matrix(y_train, y_pred_train)
conf_matrix_test = confusion_matrix(y_test, y_pred_test)

plt.figure(figsize=(14, 5))

plt.subplot(1, 2, 1)
sns.heatmap(conf_matrix_train, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix - Train')
plt.xlabel('Predicted')
plt.ylabel('True')

plt.subplot(1, 2, 2)
sns.heatmap(conf_matrix_test, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix - Test')
plt.xlabel('Predicted')
plt.ylabel('True')

plt.tight_layout()
plt.show()

# Data visualizations and bivariate charts

# Histogram for numerical features
data.hist(figsize=(12, 10))
plt.tight_layout()
plt.show()

# Count plot for categorical features
plt.figure(figsize=(12, 8))
for i, column in enumerate(categorical_columns[:-1]):
    plt.subplot(2, 3, i + 1)
    sns.countplot(x=data[column])
    plt.title(f'Distribution of {column}')
plt.tight_layout()
plt.show()

# Box plot to show the distribution of numerical features by the target class
plt.figure(figsize=(14, 8))
for i, column in enumerate(X.columns[:10]):
    plt.subplot(2, 5, i + 1)
    sns.boxplot(x=y, y=X[column])
    plt.title(f'{column} by Class')
plt.tight_layout()
plt.show()

# Pair plot for a subset of features
sns.pairplot(data.iloc[:, :10].join(data['Class/ASD Traits ']), hue='Class/ASD Traits ')
plt.show()

# Import necessary libraries
import seaborn as sns
import matplotlib.pyplot as plt

# Scatter Plot: Age_Mons vs Qchat-10-Score colored by Class/ASD Traits
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Age_Mons', y='Qchat-10-Score', hue='Class/ASD Traits ', data=data, palette='coolwarm')
plt.title('Scatter Plot: Age_Mons vs Qchat-10-Score')
plt.xlabel('Age_Mons')
plt.ylabel('Qchat-10-Score')
plt.show()

# Box Plot: Age_Mons grouped by Class/ASD Traits
plt.figure(figsize=(10, 6))
sns.boxplot(x='Class/ASD Traits ', y='Age_Mons', data=data, palette='coolwarm')
plt.title('Box Plot: Age_Mons by Class/ASD Traits')
plt.xlabel('Class/ASD Traits')
plt.ylabel('Age_Mons')
plt.show()

# Violin Plot: Qchat-10-Score grouped by Class/ASD Traits
plt.figure(figsize=(10, 6))
sns.violinplot(x='Class/ASD Traits ', y='Qchat-10-Score', data=data, palette='coolwarm')
plt.title('Violin Plot: Qchat-10-Score by Class/ASD Traits')
plt.xlabel('Class/ASD Traits')
plt.ylabel('Qchat-10-Score')
plt.show()

# Swarm Plot: A1 vs A2 colored by Class/ASD Traits
plt.figure(figsize=(10, 6))
sns.swarmplot(x='A1', y='A2', hue='Class/ASD Traits ', data=data, palette='coolwarm', dodge=True)
plt.title('Swarm Plot: A1 vs A2')
plt.xlabel('A1')
plt.ylabel('A2')
plt.show()

# Strip Plot: A4 vs A5 colored by Class/ASD Traits
plt.figure(figsize=(10, 6))
sns.stripplot(x='A4', y='A5', hue='Class/ASD Traits ', data=data, palette='coolwarm', dodge=True)
plt.title('Strip Plot: A4 vs A5')
plt.xlabel('A4')
plt.ylabel('A5')
plt.show()

# Pairwise relationships (Pair Plot): selected features
plt.figure(figsize=(12, 10))
sns.pairplot(data[['A1', 'A2', 'A3', 'A4', 'Class/ASD Traits ']], hue='Class/ASD Traits ', palette='coolwarm')
plt.show()

# Import necessary libraries
import seaborn as sns
import matplotlib.pyplot as plt

# Scatter Plot: Age_Mons vs Qchat-10-Score colored by Class/ASD Traits
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Age_Mons', y='Qchat-10-Score', hue='Class/ASD Traits ', data=data, palette='coolwarm')
plt.title('Scatter Plot: Age_Mons vs Qchat-10-Score')
plt.xlabel('Age_Mons')
plt.ylabel('Qchat-10-Score')
plt.legend(title='Class/ASD Traits')
plt.show()

# Box Plot: Age_Mons grouped by Class/ASD Traits
plt.figure(figsize=(10, 6))
sns.boxplot(x='Class/ASD Traits ', y='Age_Mons', data=data, palette='coolwarm')
plt.title('Box Plot: Age_Mons by Class/ASD Traits')
plt.xlabel('Class/ASD Traits')
plt.ylabel('Age_Mons')
plt.show()

# Violin Plot: Qchat-10-Score grouped by Class/ASD Traits
plt.figure(figsize=(10, 6))
sns.violinplot(x='Class/ASD Traits ', y='Qchat-10-Score', data=data, palette='coolwarm')
plt.title('Violin Plot: Qchat-10-Score by Class/ASD Traits')
plt.xlabel('Class/ASD Traits')
plt.ylabel('Qchat-10-Score')
plt.show()

# Swarm Plot: A1 vs A2 colored by Class/ASD Traits
plt.figure(figsize=(10, 6))
sns.swarmplot(x='A1', y='A2', hue='Class/ASD Traits ', data=data, palette='coolwarm', dodge=True)
plt.title('Swarm Plot: A1 vs A2')
plt.xlabel('A1')
plt.ylabel('A2')
plt.legend(title='Class/ASD Traits')
plt.show()

# Strip Plot: A4 vs A5 colored by Class/ASD Traits
plt.figure(figsize=(10, 6))
sns.stripplot(x='A4', y='A5', hue='Class/ASD Traits ', data=data, palette='coolwarm', dodge=True)
plt.title('Strip Plot: A4 vs A5')
plt.xlabel('A4')
plt.ylabel('A5')
plt.legend(title='Class/ASD Traits')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Box Plot: Distribution of Age_Mons by Class/ASD Traits
plt.figure(figsize=(10, 6))
sns.boxplot(x='Class/ASD Traits ', y='Age_Mons', data=data, palette='coolwarm')
plt.title('Box Plot: Age_Mons by Class/ASD Traits')
plt.xlabel('Class/ASD Traits')
plt.ylabel('Age_Mons')
plt.show()

import matplotlib.pyplot as plt

# Bar Chart: Mean Age_Mons by Class/ASD Traits
plt.figure(figsize=(10, 6))
mean_age = data.groupby('Class/ASD Traits ')['Age_Mons'].mean()
mean_age.plot(kind='bar', color='skyblue')
plt.title('Bar Chart: Mean Age_Mons by Class/ASD Traits')
plt.xlabel('Class/ASD Traits')
plt.ylabel('Mean Age_Mons')
plt.xticks(ticks=range(len(mean_age.index)), labels=label_encoders['Class/ASD Traits '].inverse_transform(mean_age.index), rotation=45)
plt.show()

import matplotlib.pyplot as plt

# Pie Chart: Proportion of each Class/ASD Traits
plt.figure(figsize=(8, 8))
class_counts = data['Class/ASD Traits '].value_counts()
plt.pie(class_counts, labels=label_encoders['Class/ASD Traits '].inverse_transform(class_counts.index), autopct='%1.1f%%', colors=sns.color_palette('pastel'))
plt.title('Pie Chart: Proportion of Class/ASD Traits')
plt.show()

"""# 2) Random Forest"""

def objective_function(features, X, y):
    features = np.array(features).astype(bool)
    if not np.any(features):  # Ensure at least one feature is selected
        return float('inf')  # Return a high value for invalid solutions
    X_selected = X[:, features]

    X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)

    clf = RandomForestClassifier(random_state=52)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    return -accuracy_score(y_test, y_pred)

# Firefly Algorithm
class FireflyAlgorithm:
    def __init__(self, objective_function, lb, ub, args=(), pop_size=20, max_iter=50, alpha=0.5, beta_min=0.2, gamma=1.0):
        self.objective_function = objective_function
        self.lb = np.array(lb)
        self.ub = np.array(ub)
        self.args = args
        self.pop_size = pop_size
        self.max_iter = max_iter
        self.alpha = alpha
        self.beta_min = beta_min
        self.gamma = gamma

    def run(self):
        dim = len(self.lb)
        population = np.random.randint(2, size=(self.pop_size, dim))
        fitness = np.apply_along_axis(self.objective_function, 1, population, *self.args)

        best_firefly = population[np.argmin(fitness)]
        best_fitness = np.min(fitness)

        for t in range(self.max_iter):
            for i in range(self.pop_size):
                for j in range(self.pop_size):
                    if fitness[i] > fitness[j]:
                        r = np.linalg.norm(population[i] - population[j])
                        beta = self.beta_min + (1 - self.beta_min) * np.exp(-self.gamma * r ** 2)
                        population[i] = population[i] + beta * (population[j] - population[i]) + \
                                        self.alpha * (np.random.rand(dim) - 0.5)
                        population[i] = np.clip(population[i], self.lb, self.ub)
                        population[i] = np.round(population[i])
                        if not np.any(population[i]):  # Ensure at least one feature is selected
                            population[i][np.random.randint(dim)] = 1
                        fitness[i] = self.objective_function(population[i], *self.args)

            best_firefly = population[np.argmin(fitness)]
            best_fitness = np.min(fitness)

        return best_firefly, best_fitness

# Define the objective function and apply FA
num_features = X_reduced.shape[1]
lb = [0] * num_features
ub = [1] * num_features

fa = FireflyAlgorithm(objective_function, lb, ub, args=(X_reduced, y), pop_size=10, max_iter=25)
best_features, _ = fa.run()

# Select best features
X_selected = X_reduced[:, best_features.astype(bool)]

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=52)

"""
**Define parameter grid for Random Forest**
"""

# Define parameter grid for Random Forest
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'bootstrap': [True, False]
}

"""**Grid search based optimization**"""

grid_search = GridSearchCV(RandomForestClassifier(random_state=52), param_grid, cv=5, n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)

# Best parameters
best_params = grid_search.best_params_

# Train the model with best parameters
best_clf = RandomForestClassifier(random_state=52, **best_params)
best_clf.fit(X_train, y_train)

# Predictions
y_pred_train = best_clf.predict(X_train)
y_pred_test = best_clf.predict(X_test)

# Accuracy
train_accuracy = accuracy_score(y_train, y_pred_train)
test_accuracy = accuracy_score(y_test, y_pred_test)

print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)
print("Best Parameters:", best_clf.get_params())
print("Best Parameters:", best_params)

# Final accuracy with selected features
y_pred = best_clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Final accuracy with selected features:", accuracy)

"""**Classification Report**"""

print("\nClassification Report (Train):")
print(classification_report(y_train, y_pred_train))
print("\nClassification Report (Test):")
print(classification_report(y_test, y_pred_test))

# Confusion Matrix
conf_matrix_train = confusion_matrix(y_train, y_pred_train)
conf_matrix_test = confusion_matrix(y_test, y_pred_test)

plt.figure(figsize=(14, 5))

plt.subplot(1, 2, 1)
sns.heatmap(conf_matrix_train, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix - Train')
plt.xlabel('Predicted')
plt.ylabel('True')

plt.subplot(1, 2, 2)
sns.heatmap(conf_matrix_test, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix - Test')
plt.xlabel('Predicted')
plt.ylabel('True')

plt.tight_layout()
plt.show()

import pickle
with open('RFmodelFF.pkl', 'wb') as file:
    pickle.dump(clf, file)

"""# 3) KNN"""

def objective_function(features, X, y):
    features = np.array(features).astype(bool)
    if not np.any(features):  # Ensure at least one feature is selected
        return float('inf')  # Return a high value for invalid solutions
    X_selected = X[:, features]

    X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)

    clf = KNeighborsClassifier()
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    return -accuracy_score(y_test, y_pred)

# Firefly Algorithm
class FireflyAlgorithm:
    def __init__(self, objective_function, lb, ub, args=(), pop_size=20, max_iter=50, alpha=0.5, beta_min=0.2, gamma=1.0):
        self.objective_function = objective_function
        self.lb = np.array(lb)
        self.ub = np.array(ub)
        self.args = args
        self.pop_size = pop_size
        self.max_iter = max_iter
        self.alpha = alpha
        self.beta_min = beta_min
        self.gamma = gamma

    def run(self):
        dim = len(self.lb)
        population = np.random.randint(2, size=(self.pop_size, dim))
        fitness = np.apply_along_axis(self.objective_function, 1, population, *self.args)

        best_firefly = population[np.argmin(fitness)]
        best_fitness = np.min(fitness)

        for t in range(self.max_iter):
            for i in range(self.pop_size):
                for j in range(self.pop_size):
                    if fitness[i] > fitness[j]:
                        r = np.linalg.norm(population[i] - population[j])
                        beta = self.beta_min + (1 - self.beta_min) * np.exp(-self.gamma * r ** 2)
                        population[i] = population[i] + beta * (population[j] - population[i]) + \
                                        self.alpha * (np.random.rand(dim) - 0.5)
                        population[i] = np.clip(population[i], self.lb, self.ub)
                        population[i] = np.round(population[i])
                        if not np.any(population[i]):  # Ensure at least one feature is selected
                            population[i][np.random.randint(dim)] = 1
                        fitness[i] = self.objective_function(population[i], *self.args)

            best_firefly = population[np.argmin(fitness)]
            best_fitness = np.min(fitness)

        return best_firefly, best_fitness

# Define the objective function and apply FA
num_features = X_reduced.shape[1]
lb = [0] * num_features
ub = [1] * num_features

fa = FireflyAlgorithm(objective_function, lb, ub, args=(X_reduced, y), pop_size=10, max_iter=25)
best_features, _ = fa.run()

# Select best features
X_selected = X_reduced[:, best_features.astype(bool)]

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=52)

"""**Define parameter grid for KNN**"""

param_grid = {
    'n_neighbors': [3, 5, 7],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']
}

"""**Grid search based optimization**"""

grid_search = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5, n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)
# Best parameters
best_params = grid_search.best_params_
# Train the model with best parameters
best_clf = KNeighborsClassifier(**best_params)
best_clf.fit(X_train, y_train)

# Predictions
y_pred_train = best_clf.predict(X_train)
y_pred_test = best_clf.predict(X_test)

# Accuracy
train_accuracy = accuracy_score(y_train, y_pred_train)
test_accuracy = accuracy_score(y_test, y_pred_test)

print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)
print("Best Parameters:", best_clf.get_params())
print("Best Parameters:", best_params)

clf = KNeighborsClassifier(**best_params)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Final accuracy with selected features:", accuracy)

"""**Classification Report**"""

print("\nClassification Report (Train):")
print(classification_report(y_train, y_pred_train))
print("\nClassification Report (Test):")
print(classification_report(y_test, y_pred_test))

# Confusion Matrix
conf_matrix_train = confusion_matrix(y_train, y_pred_train)
conf_matrix_test = confusion_matrix(y_test, y_pred_test)

plt.figure(figsize=(14, 5))

plt.subplot(1, 2, 1)
sns.heatmap(conf_matrix_train, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix - Train')
plt.xlabel('Predicted')
plt.ylabel('True')

plt.subplot(1, 2, 2)
sns.heatmap(conf_matrix_test, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix - Test')
plt.xlabel('Predicted')
plt.ylabel('True')

plt.tight_layout()
plt.show()

import pickle
with open('KNNmodelFF.pkl', 'wb') as file:
    pickle.dump(clf, file)

"""# 4) GaussianNB

**Note: Naive Bayes doesn't have hyperparameters for Grid Search like Other Classifiers.**
"""

def objective_function(features, X, y):
    features = np.array(features).astype(bool)
    if not np.any(features):  # Ensure at least one feature is selected
        return float('inf')  # Return a high value for invalid solutions
    X_selected = X[:, features]

    X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)
    clf = GaussianNB()
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    return -accuracy_score(y_test, y_pred)
# Firefly Algorithm
class FireflyAlgorithm:
    def __init__(self, objective_function, lb, ub, args=(), pop_size=20, max_iter=50, alpha=0.5, beta_min=0.2, gamma=1.0):
        self.objective_function = objective_function
        self.lb = np.array(lb)
        self.ub = np.array(ub)
        self.args = args
        self.pop_size = pop_size
        self.max_iter = max_iter
        self.alpha = alpha
        self.beta_min = beta_min
        self.gamma = gamma
    def run(self):
        dim = len(self.lb)
        population = np.random.randint(2, size=(self.pop_size, dim))
        fitness = np.apply_along_axis(self.objective_function, 1, population, *self.args)
        best_firefly = population[np.argmin(fitness)]
        best_fitness = np.min(fitness)
        for t in range(self.max_iter):
            for i in range(self.pop_size):
                for j in range(self.pop_size):
                    if fitness[i] > fitness[j]:
                        r = np.linalg.norm(population[i] - population[j])
                        beta = self.beta_min + (1 - self.beta_min) * np.exp(-self.gamma * r ** 2)
                        population[i] = population[i] + beta * (population[j] - population[i]) + \
                                        self.alpha * (np.random.rand(dim) - 0.5)
                        population[i] = np.clip(population[i], self.lb, self.ub)
                        population[i] = np.round(population[i])
                        if not np.any(population[i]):  # Ensure at least one feature is selected
                            population[i][np.random.randint(dim)] = 1
                        fitness[i] = self.objective_function(population[i], *self.args)
            best_firefly = population[np.argmin(fitness)]
            best_fitness = np.min(fitness)
        return best_firefly, best_fitness

# Define the objective function and apply FA
num_features = X_reduced.shape[1]
lb = [0] * num_features
ub = [1] * num_features
fa = FireflyAlgorithm(objective_function, lb, ub, args=(X_reduced, y), pop_size=10, max_iter=25)
best_features, _ = fa.run()

best_features

# Select best features
X_selected = X_reduced[:, best_features.astype(bool)]
# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=52)

X_selected

y

"""**Train the model**"""

clf = GaussianNB()
clf.fit(X_train, y_train)

# Predictions
y_pred_train = clf.predict(X_train)
y_pred_test = clf.predict(X_test)
# Accuracy
train_accuracy = accuracy_score(y_train, y_pred_train)
test_accuracy = accuracy_score(y_test, y_pred_test)
print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)

"""**Classification Report**"""

print("\nClassification Report (Train):")
print(classification_report(y_train, y_pred_train))
print("\nClassification Report (Test):")
print(classification_report(y_test, y_pred_test))

# Confusion Matrix
conf_matrix_train = confusion_matrix(y_train, y_pred_train)
conf_matrix_test = confusion_matrix(y_test, y_pred_test)

plt.figure(figsize=(14, 5))

plt.subplot(1, 2, 1)
sns.heatmap(conf_matrix_train, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix - Train')
plt.xlabel('Predicted')
plt.ylabel('True')

plt.subplot(1, 2, 2)
sns.heatmap(conf_matrix_test, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix - Test')
plt.xlabel('Predicted')
plt.ylabel('True')

plt.tight_layout()
plt.show()

import pickle
with open('NBmodelFF.pkl', 'wb') as file:
    pickle.dump(clf, file)

data

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix
from xgboost import XGBClassifier
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc, accuracy_score, precision_score, recall_score, f1_score

X = data.drop(['Case_No', 'Class/ASD Traits '], axis=1)
y = data['Class/ASD Traits ']
selector = SelectKBest(score_func=f_classif, k=6)
X_selected = selector.fit_transform(X, y)
selected_feature = X.columns[selector.get_support()]
print("Selected Features:", selected_feature)

