# -*- coding: utf-8 -*-
"""Particle swarm ANN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/119qN8oo0TiOlDqbck00cOUYThdokWpHR
"""

!pip install pyswarm

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from pyswarm import pso
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

data = pd.read_csv('/content/Toddler Autism dataset July 2018.csv')
data

data.columns

data.isnull().sum()

data.duplicated().sum()

data.info()

data.describe()

data.head()

plt.figure(figsize=(10, 6))
sns.histplot(data['Age_Mons'], kde=True)
plt.title('Distribution of Age in Months')
plt.xlabel('Age in Months')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='Sex', y='Qchat-10-Score', data=data)
plt.title('Qchat-10-Score Distribution by Sex')
plt.xlabel('Sex')
plt.ylabel('Qchat-10-Score')
plt.show()

plt.figure(figsize=(10, 6))
sns.countplot(x='Ethnicity', hue='Class/ASD Traits ', data=data)
plt.title('Count of ASD Traits by Ethnicity')
plt.xlabel('Ethnicity')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(12, 6))
sns.pointplot(x='Age_Mons', y='Qchat-10-Score', hue='Sex', data=data)
plt.title('Qchat-10-Score Across Different Ages in Months by Sex')
plt.xlabel('Age in Months')
plt.ylabel('Qchat-10-Score')
plt.show()

"""**Encode categorical variables**"""

label_encoders = {}
categorical_columns = ['Sex', 'Ethnicity', 'Jaundice', 'Family_mem_with_ASD', 'Who completed the test','Class/ASD Traits ']
for column in categorical_columns:
    label_encoders[column] = LabelEncoder()
    data[column] = label_encoders[column].fit_transform(data[column])

X = data.drop(['Case_No', 'Class/ASD Traits '], axis=1)
y = data['Class/ASD Traits ']

"""**Feature scaling using StandardScaler**"""

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=10)  # Adjust n_components based on the dataset
X_reduced = pca.fit_transform(X_scaled)

# Visualization of PCA explained variance
explained_variance = pca.explained_variance_ratio_
plt.figure(figsize=(8, 6))
plt.bar(range(1, len(explained_variance) + 1), explained_variance, alpha=0.7, align='center', label='individual explained variance')
plt.step(range(1, len(explained_variance) + 1), np.cumsum(explained_variance), where='mid', label='cumulative explained variance')
plt.ylabel('Explained variance ratio')
plt.xlabel('Principal components')
plt.legend(loc='best')
plt.tight_layout()
plt.show()

# Correlation matrix visualization
plt.figure(figsize=(12, 10))
sns.heatmap(data.corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix')
plt.show()

"""**Define Particle Swarm Optimization objective function for feature selection**"""

def objective_function(features, X, y):
    features = np.array(features).astype(bool)
    X_selected = X[:, features]

    X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)

    clf = MLPClassifier(max_iter=1000, random_state=42)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    return -accuracy_score(y_test, y_pred)

"""**Apply PSO**"""

num_features = X_reduced.shape[1]
lb = [0] * num_features
ub = [1] * num_features

lb

ub

best_features, _ = pso(objective_function, lb, ub, args=(X_reduced, y), swarmsize=20, maxiter=50)  # Adjust swarmsize and maxiter

"""**Select best features**"""

X_selected = X_reduced[:, best_features.astype(bool)]

# Visualization of selected features
selected_features = np.where(best_features.astype(bool))[0]
plt.figure(figsize=(12, 6))
plt.bar(selected_features, best_features[best_features.astype(bool)], align='center')
plt.xlabel('Feature index')
plt.ylabel('Selected')
plt.title('Selected Features by PSO')
plt.show()

"""**Split data into train and test sets**"""

X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)

"""**Define parameter grid for ANN**"""

param_grid = {
    'hidden_layer_sizes': [(50,), (30, 30)],
    'activation': ['relu', 'tanh'],
    'solver': ['adam', 'sgd'],
    'alpha': [0.01, 0.1],  # Increase alpha for stronger regularization
    'learning_rate': ['constant', 'adaptive']
}

"""**Grid search based optimization**"""

grid_search = GridSearchCV(MLPClassifier(max_iter=1000, random_state=42), param_grid, cv=5, n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)

# Best parameters
best_params = grid_search.best_params_

# Train the model with best parameters
best_clf = MLPClassifier(max_iter=1000, random_state=42, **best_params)
best_clf.fit(X_train, y_train)

print(best_params)

# Predictions
y_pred_train = best_clf.predict(X_train)
y_pred_test = best_clf.predict(X_test)

# Accuracy
train_accuracy = accuracy_score(y_train, y_pred_train)
test_accuracy = accuracy_score(y_test, y_pred_test)

print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)
print("Best Parameters:", best_clf.get_params())
print("Best Parameters:", best_params)

clf = MLPClassifier(max_iter=1000, random_state=42, early_stopping=True)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Final accuracy with selected features:", accuracy)

"""**Classification Report**"""

print("\nClassification Report (Train):")
print(classification_report(y_train, y_pred_train))
print("\nClassification Report (Test):")
print(classification_report(y_test, y_pred_test))

# Confusion Matrix
conf_matrix_train = confusion_matrix(y_train, y_pred_train)
conf_matrix_test = confusion_matrix(y_test, y_pred_test)

plt.figure(figsize=(14, 5))

plt.subplot(1, 2, 1)
sns.heatmap(conf_matrix_train, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix - Train')
plt.xlabel('Predicted')
plt.ylabel('True')

plt.subplot(1, 2, 2)
sns.heatmap(conf_matrix_test, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix - Test')
plt.xlabel('Predicted')
plt.ylabel('True')

plt.tight_layout()
plt.show()

