# -*- coding: utf-8 -*-
"""Without Ant and Bee

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X57txvQZHs-opn03iJ3mKwLhvV3aecgL

# CNN
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Load your datasets
train_dir = '/content/drive/MyDrive/autistic_train'
test_dir = '/content/drive/MyDrive/autistic_test'
validation_dir = '/content/drive/MyDrive/autistic_valid'

# Image Data Generators
train_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)
validation_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(train_dir, target_size=(150, 150), batch_size=20, class_mode='binary')
validation_generator = validation_datagen.flow_from_directory(validation_dir, target_size=(150, 150), batch_size=20, class_mode='binary')
test_generator = test_datagen.flow_from_directory(test_dir, target_size=(150, 150), batch_size=20, class_mode='binary', shuffle=False)

# Function to create model
def create_model(optimizer='adam', dropout_rate=0.5):
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', input_shape=(150, 150, 3)),
        MaxPooling2D(2, 2),
        Conv2D(64, (3, 3), activation='relu'),
        MaxPooling2D(2, 2),
        Conv2D(128, (3, 3), activation='relu'),
        MaxPooling2D(2, 2),
        Flatten(),
        Dense(512, activation='relu'),
        Dropout(dropout_rate),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
    return model
# Define hyperparameters to tune
batch_sizes = [10, 40]
epochs_list = [5, 8]
optimizers = ['adam']
dropout_rates = [0.3]
best_accuracy = 0
best_params = {}
# Perform Grid Search manually
for batch_size in batch_sizes:
    for epochs in epochs_list:
        for optimizer in optimizers:
            for dropout_rate in dropout_rates:
                print(f'Training with batch_size={batch_size}, epochs={epochs}, optimizer={optimizer}, dropout_rate={dropout_rate}')
                model = create_model(optimizer=optimizer, dropout_rate=dropout_rate)
                model.fit(train_generator, validation_data=validation_generator, epochs=epochs, batch_size=batch_size, verbose=1)
                val_loss, val_acc = model.evaluate(validation_generator)
                print(f'Validation accuracy: {val_acc}')
                if val_acc > best_accuracy:
                    best_accuracy = val_acc
                    best_params = {
                        'batch_size': batch_size,
                        'epochs': epochs,
                        'optimizer': optimizer,
                        'dropout_rate': dropout_rate
                    }
print(f'Best params: {best_params}')
print(f'Best validation accuracy: {best_accuracy}')
# Train the best model
best_model = create_model(optimizer=best_params['optimizer'], dropout_rate=best_params['dropout_rate'])
best_model.fit(train_generator, validation_data=validation_generator, epochs=best_params['epochs'], batch_size=best_params['batch_size'], verbose=1)
# Evaluate the best model using the test set
test_loss, test_acc = best_model.evaluate(test_generator)
print("Test Accuracy: ", test_acc)

# Predict the classes of the test set
Y_pred = best_model.predict(test_generator)
y_pred = np.where(Y_pred > 0.5, 1, 0).flatten()

# True labels
y_true = test_generator.classes

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
print('Confusion Matrix')
print(cm)

# Plot confusion matrix
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=test_generator.class_indices, yticklabels=test_generator.class_indices)
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.show()

# Classification Report
print('Classification Report')
print(classification_report(y_true, y_pred, target_names=list(test_generator.class_indices.keys())))

# Classification Metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'F1 Score: {f1}')

best_model.save('CNN.h5')

"""# VGG"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Input
from tensorflow.keras.applications import VGG16
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Load your datasets
train_dir = '/content/drive/MyDrive/autistic_train'
test_dir = '/content/drive/MyDrive/autistic_test'
validation_dir = '/content/drive/MyDrive/autistic_valid'

# Image Data Generators
train_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)
validation_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(train_dir, target_size=(150, 150), batch_size=20, class_mode='binary')
validation_generator = validation_datagen.flow_from_directory(validation_dir, target_size=(150, 150), batch_size=20, class_mode='binary')
test_generator = test_datagen.flow_from_directory(test_dir, target_size=(150, 150), batch_size=20, class_mode='binary', shuffle=False)

# Function to create VGG model
def create_vgg_model(optimizer='adam', dropout_rate=0.5):
    base_model = VGG16(weights='imagenet', include_top=False, input_shape=(150, 150, 3))
    for layer in base_model.layers:
        layer.trainable = False
    x = base_model.output
    x = Flatten()(x)
    x = Dense(512, activation='relu')(x)
    x = Dropout(dropout_rate)(x)
    predictions = Dense(1, activation='sigmoid')(x)
    model = Model(inputs=base_model.input, outputs=predictions)
    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
    return model

# Define hyperparameters to tune
batch_sizes = [10, 40]
epochs_list = [5, 8]
optimizers = ['adam']
dropout_rates = [0.3]

best_accuracy = 0
best_params = {}

# Perform Grid Search manually
for batch_size in batch_sizes:
    for epochs in epochs_list:
        for optimizer in optimizers:
            for dropout_rate in dropout_rates:
                print(f'Training with batch_size={batch_size}, epochs={epochs}, optimizer={optimizer}, dropout_rate={dropout_rate}')
                model = create_vgg_model(optimizer=optimizer, dropout_rate=dropout_rate)
                model.fit(train_generator, validation_data=validation_generator, epochs=epochs, batch_size=batch_size, verbose=1)
                val_loss, val_acc = model.evaluate(validation_generator)
                print(f'Validation accuracy: {val_acc}')
                if val_acc > best_accuracy:
                    best_accuracy = val_acc
                    best_params = {
                        'batch_size': batch_size,
                        'epochs': epochs,
                        'optimizer': optimizer,
                        'dropout_rate': dropout_rate
                    }

print(f'Best params: {best_params}')
print(f'Best validation accuracy: {best_accuracy}')

# Train the best model
best_model = create_vgg_model(optimizer=best_params['optimizer'], dropout_rate=best_params['dropout_rate'])
best_model.fit(train_generator, validation_data=validation_generator, epochs=best_params['epochs'], batch_size=best_params['batch_size'], verbose=1)

# Evaluate the best model using the test set
test_loss, test_acc = best_model.evaluate(test_generator)
print("Test Accuracy: ", test_acc)

# Predict the classes of the test set
Y_pred = best_model.predict(test_generator)
y_pred = np.where(Y_pred > 0.5, 1, 0).flatten()

# True labels
y_true = test_generator.classes

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
print('Confusion Matrix')
print(cm)

# Plot confusion matrix
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=test_generator.class_indices, yticklabels=test_generator.class_indices)
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.show()

# Classification Report
print('Classification Report')
print(classification_report(y_true, y_pred, target_names=list(test_generator.class_indices.keys())))

# Classification Metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'F1 Score: {f1}')

best_model.save('VGG.h5')

"""# RESNET"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Flatten, Dense, Dropout
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Load your datasets
train_dir = '/content/drive/MyDrive/autistic_train'
test_dir = '/content/drive/MyDrive/autistic_test'
validation_dir = '/content/drive/MyDrive/autistic_valid'

# Image Data Generators
train_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)
validation_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(train_dir, target_size=(150, 150), batch_size=20, class_mode='binary')
validation_generator = validation_datagen.flow_from_directory(validation_dir, target_size=(150, 150), batch_size=20, class_mode='binary')
test_generator = test_datagen.flow_from_directory(test_dir, target_size=(150, 150), batch_size=20, class_mode='binary', shuffle=False)

# Function to create ResNet model
def create_resnet_model(optimizer='adam', dropout_rate=0.5):
    base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(150, 150, 3))
    for layer in base_model.layers:
        layer.trainable = False
    x = base_model.output
    x = Flatten()(x)
    x = Dense(512, activation='relu')(x)
    x = Dropout(dropout_rate)(x)
    predictions = Dense(1, activation='sigmoid')(x)
    model = Model(inputs=base_model.input, outputs=predictions)
    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
    return model

# Define hyperparameters to tune
batch_sizes = [10, 40]
epochs_list = [5, 8]
optimizers = ['adam']
dropout_rates = [0.3]

best_accuracy = 0
best_params = {}

# Perform Grid Search manually
for batch_size in batch_sizes:
    for epochs in epochs_list:
        for optimizer in optimizers:
            for dropout_rate in dropout_rates:
                print(f'Training with batch_size={batch_size}, epochs={epochs}, optimizer={optimizer}, dropout_rate={dropout_rate}')
                model = create_resnet_model(optimizer=optimizer, dropout_rate=dropout_rate)
                model.fit(train_generator, validation_data=validation_generator, epochs=epochs, batch_size=batch_size, verbose=1)
                val_loss, val_acc = model.evaluate(validation_generator)
                print(f'Validation accuracy: {val_acc}')
                if val_acc > best_accuracy:
                    best_accuracy = val_acc
                    best_params = {
                        'batch_size': batch_size,
                        'epochs': epochs,
                        'optimizer': optimizer,
                        'dropout_rate': dropout_rate
                    }

print(f'Best params: {best_params}')
print(f'Best validation accuracy: {best_accuracy}')

# Train the best model
best_model = create_resnet_model(optimizer=best_params['optimizer'], dropout_rate=best_params['dropout_rate'])
best_model.fit(train_generator, validation_data=validation_generator, epochs=best_params['epochs'], batch_size=best_params['batch_size'], verbose=1)

# Evaluate the best model using the test set
test_loss, test_acc = best_model.evaluate(test_generator)
print("Test Accuracy: ", test_acc)

# Predict the classes of the test set
Y_pred = best_model.predict(test_generator)
y_pred = np.where(Y_pred > 0.5, 1, 0).flatten()

# True labels
y_true = test_generator.classes

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
print('Confusion Matrix')
print(cm)

# Plot confusion matrix
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=test_generator.class_indices, yticklabels=test_generator.class_indices)
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.show()

# Classification Report
print('Classification Report')
print(classification_report(y_true, y_pred, target_names=list(test_generator.class_indices.keys())))

# Classification Metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'F1 Score: {f1}')

best_model.save('RESNET.h5')