# -*- coding: utf-8 -*-
"""Without swarm AND  fire fly

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1idjUj4-JpjpJ6b96C7hNIxQyC9KZhe5o
"""

from google.colab import drive
drive.mount('/content/drive')

"""# ANN"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import classification_report, confusion_matrix
import itertools
import numpy as np

# Load dataset
df = pd.read_csv('/content/drive/MyDrive/Toddler Autism dataset July 2018.csv')

# Extract features and target variable
X = df.drop(columns=['Case_No', 'Class/ASD Traits '])
y = df['Class/ASD Traits ']

# Encode categorical variables
categorical_columns = ['Sex', 'Ethnicity', 'Jaundice', 'Family_mem_with_ASD', 'Who completed the test']
X = pd.get_dummies(X, columns=categorical_columns)

# Encode target variable
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

def create_model(optimizer='adam', init='glorot_uniform'):
    model = Sequential()
    model.add(Dense(12, input_dim=X_train.shape[1], kernel_initializer=init, activation='relu'))
    model.add(Dense(8, kernel_initializer=init, activation='relu'))
    model.add(Dense(1, kernel_initializer=init, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model

# Define the grid search parameters
batch_size_options = [10, 20]
epochs_options = [50]
optimizer_options = ['Adam']
init_options = ['glorot_uniform', 'normal', 'uniform']

best_score = 0
best_params = {}

# Perform grid search
for batch_size, epochs, optimizer, init in itertools.product(batch_size_options, epochs_options, optimizer_options, init_options):
    model = create_model(optimizer=optimizer, init=init)
    model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, verbose=0)
    _, accuracy = model.evaluate(X_test, y_test, verbose=0)

    if accuracy > best_score:
        best_score = accuracy
        best_params = {'batch_size': batch_size, 'epochs': epochs, 'optimizer': optimizer, 'init': init}

    print(f"Params: batch_size={batch_size}, epochs={epochs}, optimizer={optimizer}, init={init}, Test Accuracy={accuracy:.4f}")

print(f"Best Score: {best_score:.4f}")
print(f"Best Params: {best_params}")

# Create a new model with the best parameters
optimized_model = create_model(optimizer=best_params['optimizer'], init=best_params['init'])

# Train the model
optimized_model.fit(X_train, y_train, epochs=best_params['epochs'], batch_size=best_params['batch_size'], verbose=0)

# Evaluate the model
loss, accuracy = optimized_model.evaluate(X_test, y_test, verbose=0)
print(f"Test Accuracy: {accuracy:.4f}")
# Predict the labels for the test set
y_pred = (optimized_model.predict(X_test) > 0.5).astype("int32")

# Classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

import joblib

# Assuming your model variable is named `model`
joblib.dump(optimized_model, 'SmodelANN.pkl')

"""# RANDOM FOREST"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Load dataset
df = pd.read_csv('/content/drive/MyDrive/Toddler Autism dataset July 2018.csv')

# Extract features and target variable
X = df.drop(columns=['Case_No', 'Class/ASD Traits '])
y = df['Class/ASD Traits ']

# Encode categorical variables
categorical_columns = ['Sex', 'Ethnicity', 'Jaundice', 'Family_mem_with_ASD', 'Who completed the test']
X = pd.get_dummies(X, columns=categorical_columns)

# Encode target variable
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define the grid search parameters
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth': [4, 6, 8, 10, 12],
    'criterion': ['gini', 'entropy']
}

# Create a Random Forest model
rf_model = RandomForestClassifier(random_state=42)

# Perform grid search
grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=3, n_jobs=-1, verbose=2)
grid_result = grid_search.fit(X_train, y_train)

# Summarize results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Mean={mean:.4f} with Std={stdev:.4f} with: {param}")

# Get the best model parameters
best_params = grid_result.best_params_

# Create a new Random Forest model with the best parameters
optimized_rf_model = RandomForestClassifier(
    n_estimators=best_params['n_estimators'],
    max_features=best_params['max_features'],
    max_depth=best_params['max_depth'],
    criterion=best_params['criterion'],
    random_state=42
)

# Train the model
optimized_rf_model.fit(X_train, y_train)

# Evaluate the model
accuracy = optimized_rf_model.score(X_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")
from sklearn.metrics import classification_report, confusion_matrix

# Make predictions on the test set
y_pred = optimized_rf_model.predict(X_test)

# Print the classification report
print(classification_report(y_test, y_pred))

# Print the confusion matrix
print(confusion_matrix(y_test, y_pred))

"""# KNN"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix

# Load dataset
df = pd.read_csv('/content/drive/MyDrive/Toddler Autism dataset July 2018.csv')

# Extract features and target variable
X = df.drop(columns=['Case_No', 'Class/ASD Traits '])
y = df['Class/ASD Traits ']

# Encode categorical variables
categorical_columns = ['Sex', 'Ethnicity', 'Jaundice', 'Family_mem_with_ASD', 'Who completed the test']
X = pd.get_dummies(X, columns=categorical_columns)

# Encode target variable
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define the grid search parameters
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan', 'minkowski']
}

# Create a KNN model
knn_model = KNeighborsClassifier()

# Perform grid search
grid_search = GridSearchCV(estimator=knn_model, param_grid=param_grid, cv=3, n_jobs=-1, verbose=2)
grid_result = grid_search.fit(X_train, y_train)

# Summarize results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Mean={mean:.4f} with Std={stdev:.4f} with: {param}")

# Get the best model parameters
best_params = grid_result.best_params_

# Create a new KNN model with the best parameters
optimized_knn_model = KNeighborsClassifier(
    n_neighbors=best_params['n_neighbors'],
    weights=best_params['weights'],
    metric=best_params['metric']
)

# Train the model
optimized_knn_model.fit(X_train, y_train)

# Evaluate the model
accuracy = optimized_knn_model.score(X_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")

# Predict the labels for the test set
y_pred = optimized_knn_model.predict(X_test)

# Classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

"""# GaussianNB"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.naive_bayes import GaussianNB

# Load dataset
df = pd.read_csv('/content/drive/MyDrive/Toddler Autism dataset July 2018.csv')

# Extract features and target variable
X = df.drop(columns=['Case_No', 'Class/ASD Traits '])
y = df['Class/ASD Traits ']

# Encode categorical variables
categorical_columns = ['Sex', 'Ethnicity', 'Jaundice', 'Family_mem_with_ASD', 'Who completed the test']
X = pd.get_dummies(X, columns=categorical_columns)

# Encode target variable
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Create and train the GaussianNB model
gnb = GaussianNB()
gnb.fit(X_train, y_train)

# Evaluate the model
y_pred = gnb.predict(X_test)

# Classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

